apiVersion: v1
kind: Service
metadata:
  name: {{ include "zen-flow.fullname" . }}-metrics
  namespace: {{ include "zen-flow.namespace" . }}
  labels:
    {{- include "zen-flow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
    {{- if .Values.webhook.enabled }}
    - port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.webhookTargetPort }}
      protocol: TCP
      name: webhook
    {{- end }}
  selector:
    {{- include "zen-flow.selectorLabels" . | nindent 4 }}
{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zen-flow.fullname" . }}-webhook
  namespace: {{ include "zen-flow.namespace" . }}
  labels:
    {{- include "zen-flow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
  selector:
    {{- include "zen-flow.selectorLabels" . | nindent 4 }}
{{- end }}

