apiVersion: v1
entries:
  zen-flow:
  - annotations:
      category: Workflow
    apiVersion: v2
    appVersion: 0.0.1-alpha
    created: "2025-12-29T13:03:40.998441223Z"
    description: A Helm chart for zen-flow - Kubernetes-native job orchestration controller
    digest: c07c181f4cc254d060bf4fd4cc39ba78314b79843c5ba6ce4574c3f459c6beec
    home: https://github.com/kube-zen/zen-flow
    keywords:
    - kubernetes
    - workflow
    - job-orchestration
    - dag
    - batch-processing
    maintainers:
    - email: team@kube-zen.io
      name: Kube-ZEN Team
    name: zen-flow
    sources:
    - https://github.com/kube-zen/zen-flow
    type: application
    urls:
    - https://kube-zen.github.io/zen-flow/charts/zen-flow-0.0.1-alpha.tgz
    version: 0.0.1-alpha
generated: "2025-12-29T13:03:40.996780176Z"
